-- Seed data for Regions
INSERT INTO regions (item, item_full_name, ad_full_name) VALUES
('CN', 'CN', 'CN'),
('ID', 'ID', 'ID'),
('IN', 'IN', 'IN'),
('MY', 'MY', 'MY'),
('SG', 'SG', 'SG'),
('TH', 'TH', 'TH');

-- Seed data for Companies
INSERT INTO companies (item, item_full_name, ad_full_name) VALUES
('1000 - Sunningdale Tech Ltd', '1000 - Sunningdale Tech Ltd', '1000 - Sunningdale Tech Ltd');

-- Seed data for Locations
INSERT INTO locations (item, item_full_name, ad_full_name) VALUES
('CWO', 'CWO', 'CWO'),
('FEGZ', 'FEGZ', 'FEGZ'),
('FEQ', 'FEQ', 'FEQ'),
('FESH', 'FESH', 'FESH'),
('FESZ', 'FESZ', 'FESZ'),
('FETC', 'FETC', 'FETC'),
('OTS', 'OTS', 'OTS'),
('SCZ', 'SCZ', 'SCZ'),
('STJ', 'STJ', 'STJ'),
('STB', 'STB', 'STB'),
('FEPI', 'FEPI', 'FEPI'),
('FEPM', 'FEPM', 'FEPM'),
('SDP', 'SDP', 'SDP'),
('STM', 'STM', 'STM'),
('STP', 'STP', 'STP'),
('STT', 'STT', 'STT'),
('SG1', 'SG1', 'SG1'),
('SG18', 'SG18', 'SG18'),
('SG25', 'SG25', 'SG25'),
('SG51', 'SG51', 'SG51'),
('SGGUL1', 'SGGUL1', 'SGGUL1'),
('SGGUL9', 'SGGUL9', 'SGGUL9'),
('SGGUL164', 'SGGUL164', 'SGGUL164'),
('SDP01B', 'SDP01B', 'SDP01B');

-- Seed data for Departments
INSERT INTO departments (item, item_full_name, ad_full_name) VALUES
('ADM - Admin', 'ADM - Admin', 'ADM - Admin'),
('ASMT - Mold Assembly', 'ASMT - Mold Assembly', 'ASMT - Mold Assembly'),
('ASSM - Assembly', 'ASSM - Assembly', 'ASSM - Assembly'),
('AUTO - Automation', 'AUTO - Automation', 'AUTO - Automation'),
('BD - Business Development', 'BD - Business Development', 'BD - Business Development'),
('BPD - Business Process Development', 'BPD - Business Process Development', 'BPD - Business Process Development'),
('BRZ - Brazil Overseas Support', 'BRZ - Brazil Overseas Support', 'BRZ - Brazil Overseas Support'),
('BTM - Batam Overseas Support', 'BTM - Batam Overseas Support', 'BTM - Batam Overseas Support'),
('CA - Contract Assembly - CP', 'CA - Contract Assembly - CP', 'CA - Contract Assembly - CP'),
('CAAM - CA Admin / Mgt', 'CAAM - CA Admin / Mgt', 'CAAM - CA Admin / Mgt'),
('CAD - CAD', 'CAD - CAD', 'CAD - CAD'),
('CAP - CA Production', 'CAP - CA Production', 'CAP - CA Production'),
('CM - Custom', 'CM - Custom', 'CM - Custom'),
('CON - Contractor', 'CON - Contractor', 'CON - Contractor'),
('COR - Corporate Management', 'COR - Corporate Management', 'COR - Corporate Management'),
('CR - Cleanroom', 'CR - Cleanroom', 'CR - Cleanroom'),
('CS - Customer Service', 'CS - Customer Service', 'CS - Customer Service'),
('CW - Chi Wo Group Overseas Support', 'CW - Chi Wo Group Overseas Support', 'CW - Chi Wo Group Overseas Support'),
('CZ - Chuzhou Overseas Support', 'CZ - Chuzhou Overseas Support', 'CZ - Chuzhou Overseas Support'),
('DSGN - Design', 'DSGN - Design', 'DSGN - Design'),
('DUMMY - Dummy Overseas Operations', 'DUMMY - Dummy Overseas Operations', 'DUMMY - Dummy Overseas Operations'),
('EMPM - Export Molding Project Management', 'EMPM - Export Molding Project Management', 'EMPM - Export Molding Project Management'),
('ENG - Engineering', 'ENG - Engineering', 'ENG - Engineering'),
('ENG-LAB - Engineering-Lab (Laboratory)', 'ENG-LAB - Engineering-Lab (Laboratory)', 'ENG-LAB - Engineering-Lab (Laboratory)'),
('ENGT - Engineering - Tooling', 'ENGT - Engineering - Tooling', 'ENGT - Engineering - Tooling'),
('FAC - Facilities', 'FAC - Facilities', 'FAC - Facilities'),
('FEGZ - FEGZ Overseas Support', 'FEGZ - FEGZ Overseas Support', 'FEGZ - FEGZ Overseas Support'),
('FEL - First Engineering Ltd', 'FEL - First Engineering Ltd', 'FEL - First Engineering Ltd'),
('FEPI - FEPI Overseas Support', 'FEPI - FEPI Overseas Support', 'FEPI - FEPI Overseas Support'),
('FEPM - FEPM Overseas Support', 'FEPM - FEPM Overseas Support', 'FEPM - FEPM Overseas Support'),
('FESH - FESH Overseas Support', 'FESH - FESH Overseas Support', 'FESH - FESH Overseas Support'),
('FIM - Film Insert Molding', 'FIM - Film Insert Molding', 'FIM - Film Insert Molding'),
('FIN - Finance', 'FIN - Finance', 'FIN - Finance'),
('FINO - Finance Overseas', 'FINO - Finance Overseas', 'FINO - Finance Overseas'),
('FO - Front Office', 'FO - Front Office', 'FO - Front Office'),
('GPT - GPT', 'GPT - GPT', 'GPT - GPT'),
('HRA - HR & Admin', 'HRA - HR & Admin', 'HRA - HR & Admin'),
('IM - Injection Molding', 'IM - Injection Molding', 'IM - Injection Molding'),
('IT - IT', 'IT - IT', 'IT - IT'),
('LAC - Lacquering (Spray Painting)', 'LAC - Lacquering (Spray Painting)', 'LAC - Lacquering (Spray Painting)'),
('LAT - Latvia Overseas Support', 'LAT - Latvia Overseas Support', 'LAT - Latvia Overseas Support'),
('LOG - Logistic', 'LOG - Logistic', 'LOG - Logistic'),
('LSR - Laser Cutting', 'LSR - Laser Cutting', 'LSR - Laser Cutting'),
('MA - Materials', 'MA - Materials', 'MA - Materials'),
('MAM - Molding Admin / Mgt', 'MAM - Molding Admin / Mgt', 'MAM - Molding Admin / Mgt'),
('MATR - Material Room', 'MATR - Material Room', 'MATR - Material Room'),
('MCHT - Machining', 'MCHT - Machining', 'MCHT - Machining'),
('MED - Medical', 'MED - Medical', 'MED - Medical'),
('MFGT - Manufacturing - Tooling', 'MFGT - Manufacturing - Tooling', 'MFGT - Manufacturing - Tooling'),
('MLD - Molding', 'MLD - Molding', 'MLD - Molding'),
('MM - Mars', 'MM - Mars', 'MM - Mars'),
('MM-DESIGN - MM-Design', 'MM-DESIGN - MM-Design', 'MM-DESIGN - MM-Design'),
('MMFTG - Mold Manufacturing', 'MMFTG - Mold Manufacturing', 'MMFTG - Mold Manufacturing'),
('MT - Mold Trial', 'MT - Mold Trial', 'MT - Mold Trial'),
('MTN - Maintenance', 'MTN - Maintenance', 'MTN - Maintenance'),
('MX - Mexico Overseas Support', 'MX - Mexico Overseas Support', 'MX - Mexico Overseas Support'),
('OP - Operations', 'OP - Operations', 'OP - Operations'),
('PDY - Podoyo Group Overseas Support', 'PDY - Podoyo Group Overseas Support', 'PDY - Podoyo Group Overseas Support'),
('PGM - Program Management', 'PGM - Program Management', 'PGM - Program Management'),
('PPC - PP&C', 'PPC - PP&C', 'PPC - PP&C'),
('PUR - Purchasing', 'PUR - Purchasing', 'PUR - Purchasing'),
('QA - Quality Assurance', 'QA - Quality Assurance', 'QA - Quality Assurance'),
('QAPT - QA - Tooling', 'QAPT - QA - Tooling', 'QAPT - QA - Tooling'),
('QS - Quality System', 'QS - Quality System', 'QS - Quality System'),
('RD - R&D', 'RD - R&D', 'RD - R&D'),
('RDA - Applied Inno', 'RDA - Applied Inno', 'RDA - Applied Inno'),
('RDI - Inno Design', 'RDI - Inno Design', 'RDI - Inno Design'),
('RIG - SIA Riga Overseas Support', 'RIG - SIA Riga Overseas Support', 'RIG - SIA Riga Overseas Support'),
('SAM - Secondary Operation Admin / Mgt', 'SAM - Secondary Operation Admin / Mgt', 'SAM - Secondary Operation Admin / Mgt'),
('SDP - SDP Overseas Support', 'SDP - SDP Overseas Support', 'SDP - SDP Overseas Support'),
('SEN013 - SENIOR FA ENGINEER', 'SEN013 - SENIOR FA ENGINEER', 'SEN013 - SENIOR FA ENGINEER'),
('SH - Shanghai Overseas Support', 'SH - Shanghai Overseas Support', 'SH - Shanghai Overseas Support'),
('SITC - Innovation Tech Centre', 'SITC - Innovation Tech Centre', 'SITC - Innovation Tech Centre'),
('SP - Secondary Porcess', 'SP - Secondary Porcess', 'SP - Secondary Porcess'),
('SPCZ - Chuzhou Overseas Support', 'SPCZ - Chuzhou Overseas Support', 'SPCZ - Chuzhou Overseas Support'),
('SPI - SPI', 'SPI - SPI', 'SPI - SPI'),
('STP - Penang Overseas Support', 'STP - Penang Overseas Support', 'STP - Penang Overseas Support'),
('SZ - Suzhou Overseas Support', 'SZ - Suzhou Overseas Support', 'SZ - Suzhou Overseas Support'),
('TAM - Toolroom Admin / Mgt', 'TAM - Toolroom Admin / Mgt', 'TAM - Toolroom Admin / Mgt'),
('TH - Thailand Overseas Support', 'TH - Thailand Overseas Support', 'TH - Thailand Overseas Support'),
('TI - Tertiary Institution', 'TI - Tertiary Institution', 'TI - Tertiary Institution'),
('TJ - Tianjin Overseas Support', 'TJ - Tianjin Overseas Support', 'TJ - Tianjin Overseas Support'),
('TLRM - Toolroom', 'TLRM - Toolroom', 'TLRM - Toolroom'),
('TMTN - Tooling Maintenance', 'TMTN - Tooling Maintenance', 'TMTN - Tooling Maintenance'),
('TPO - Tampo', 'TPO - Tampo', 'TPO - Tampo'),
('USA - USA Overseas Support', 'USA - USA Overseas Support', 'USA - USA Overseas Support'),
('WH - Warehouse', 'WH - Warehouse', 'WH - Warehouse');

-- Seed data for Job Titles (Partial list for brevity, user can add more)
INSERT INTO job_titles (item, item_full_name, ad_full_name) VALUES
('Chairman', 'Chairman', 'Chairman'),
('Asst Accountant', 'Asst Accountant', 'Asst Accountant'),
('Assistant Accountant - Tax', 'Assistant Accountant - Tax', 'Assistant Accountant - Tax'),
('Accounts Assistant', 'Accounts Assistant', 'Accounts Assistant'),
('Accountant', 'Accountant', 'Accountant'),
('Accountant - Tax', 'Accountant - Tax', 'Accountant - Tax'),
('Accountant - Costing', 'Accountant - Costing', 'Accountant - Costing'),
('Accountant - AR/AP', 'Accountant - AR/AP', 'Accountant - AR/AP'),
('Admin Assistant', 'Admin Assistant', 'Admin Assistant'),
('Admin Assistant I - Doc Control', 'Admin Assistant I - Doc Control', 'Admin Assistant I - Doc Control'),
('Admin Assistant I - HR', 'Admin Assistant I - HR', 'Admin Assistant I - HR'),
('Admin Assistant I - Production', 'Admin Assistant I - Production', 'Admin Assistant I - Production');
-- ... (Add more job titles as needed)
