-- Seed departments table
-- item = display name, item_full_name = coded value stored in JSON payload
INSERT INTO departments (item, item_full_name, sort_order) VALUES
('Admin', 'ADM - Admin', 10),
('Mold Assembly', 'ASMT - Mold Assembly', 20),
('Assembly', 'ASSM - Assembly', 30),
('Automation', 'AUTO - Automation', 40),
('Business Development', 'BD - Business Development', 50),
('Business Process Development', 'BPD - Business Process Development', 60),
('Brazil Overseas Support', 'BRZ - Brazil Overseas Support', 70),
('Batam Overseas Support', 'BTM - Batam Overseas Support', 80),
('Contract Assembly - CP', 'CA - Contract Assembly - CP', 90),
('CA Admin / Mgt', 'CAAM - CA Admin / Mgt', 100),
('CAD', 'CAD - CAD', 110),
('CA Production', 'CAP - CA Production', 120),
('Custom', 'CM - Custom', 130),
('Contractor', 'CON - Contractor', 140),
('Corporate Management', 'COR - Corporate Management', 150),
('Cleanroom', 'CR - Cleanroom', 160),
('Customer Service', 'CS - Customer Service', 170),
('Chi Wo Group Overseas Support', 'CW - Chi Wo Group Overseas Support', 180),
('Chuzhou Overseas Support', 'CZ - Chuzhou Overseas Support', 190),
('Design', 'DSGN - Design', 200),
('Dummy Overseas Operations', 'DUMMY - Dummy Overseas Operations', 210),
('Export Molding Project Management', 'EMPM - Export Molding Project Management', 220),
('Engineering', 'ENG - Engineering', 230),
('Engineering-Lab (Laboratory)', 'ENG-LAB - Engineering-Lab (Laboratory)', 240),
('Engineering - Tooling', 'ENGT - Engineering - Tooling', 250),
('Facilities', 'FAC - Facilities', 260),
('FEGZ Overseas Support', 'FEGZ - FEGZ Overseas Support', 270),
('First Engineering Ltd', 'FEL - First Engineering Ltd', 280),
('FEPI Overseas Support', 'FEPI - FEPI Overseas Support', 290),
('FEPM Overseas Support', 'FEPM - FEPM Overseas Support', 300),
('FESH Overseas Support', 'FESH - FESH Overseas Support', 310),
('Film Insert Molding', 'FIM - Film Insert Molding', 320),
('Finance', 'FIN - Finance', 330),
('Finance Overseas', 'FINO - Finance Overseas', 340),
('Front Office', 'FO - Front Office', 350),
('GPT', 'GPT - GPT', 360),
('HR & Admin', 'HRA - HR & Admin', 370),
('Injection Molding', 'IM - Injection Molding', 380),
('IT', 'IT - IT', 390),
('Lacquering (Spray Painting)', 'LAC - Lacquering (Spray Painting)', 400),
('Latvia Overseas Support', 'LAT - Latvia Overseas Support', 410),
('Logistic', 'LOG - Logistic', 420),
('Laser Cutting', 'LSR - Laser Cutting', 430),
('Materials', 'MA - Materials', 440),
('Molding Admin / Mgt', 'MAM - Molding Admin / Mgt', 450),
('Material Room', 'MATR - Material Room', 460),
('Machining', 'MCHT - Machining', 470),
('Medical', 'MED - Medical', 480),
('Manufacturing - Tooling', 'MFGT - Manufacturing - Tooling', 490),
('Molding', 'MLD - Molding', 500),
('Mars', 'MM - Mars', 510),
('MM-Design', 'MM-DESIGN - MM-Design', 520),
('Mold Manufacturing', 'MMFTG - Mold Manufacturing', 530),
('Mold Trial', 'MT - Mold Trial', 540),
('Maintenance', 'MTN - Maintenance', 550),
('Mexico Overseas Support', 'MX - Mexico Overseas Support', 560),
('Operations', 'OP - Operations', 570),
('Podoyo Group Overseas Support', 'PDY - Podoyo Group Overseas Support', 580),
('Program Management', 'PGM - Program Management', 590),
('PP&C', 'PPC - PP&C', 600),
('Purchasing', 'PUR - Purchasing', 610),
('Quality Assurance', 'QA - Quality Assurance', 620),
('QA - Tooling', 'QAPT - QA - Tooling', 630),
('Quality System', 'QS - Quality System', 640),
('R&D', 'RD - R&D', 650),
('Applied Inno', 'RDA - Applied Inno', 660),
('Inno Design', 'RDI - Inno Design', 670),
('SIA Riga Overseas Support', 'RIG - SIA Riga Overseas Support', 680),
('Secondary Operation Admin / Mgt', 'SAM - Secondary Operation Admin / Mgt', 690),
('SDP Overseas Support', 'SDP - SDP Overseas Support', 700),
('SENIOR FA ENGINEER', 'SEN013 - SENIOR FA ENGINEER', 710),
('Shanghai Overseas Support', 'SH - Shanghai Overseas Support', 720),
('Innovation Tech Centre', 'SITC - Innovation Tech Centre', 730),
('Secondary Process', 'SP - Secondary Porcess', 740),
('Chuzhou Overseas Support (SPCZ)', 'SPCZ - Chuzhou Overseas Support', 750),
('SPI', 'SPI - SPI', 760),
('Penang Overseas Support', 'STP - Penang Overseas Support', 770),
('Suzhou Overseas Support', 'SZ - Suzhou Overseas Support', 780),
('Toolroom Admin / Mgt', 'TAM - Toolroom Admin / Mgt', 790),
('Thailand Overseas Support', 'TH - Thailand Overseas Support', 800),
('Tertiary Institution', 'TI - Tertiary Institution', 810),
('Tianjin Overseas Support', 'TJ - Tianjin Overseas Support', 820),
('Toolroom', 'TLRM - Toolroom', 830),
('Tooling Maintenance', 'TMTN - Tooling Maintenance', 840),
('Tampo', 'TPO - Tampo', 850),
('USA Overseas Support', 'USA - USA Overseas Support', 860),
('Warehouse', 'WH - Warehouse', 870)
ON CONFLICT (item) DO UPDATE SET
    item_full_name = EXCLUDED.item_full_name,
    sort_order     = EXCLUDED.sort_order;
